In [10]:
from sklearn import preprocessing
import numpy as np

In [11]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [12]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_standarized = standardizer.fit_transform(X_train)

In [13]:
print(X_train_standarized)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [15]:
print(X_train_2)

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [20]:
# Aplicamos los métodos "fit" y "transform" por separado
standardizer = preprocessing.StandardScaler()

# Método fit a los datos de entrenamiento 2.
sf = standardizer.fit(X_train_2)

# Método transform para los datos de entrenamiento 2.
X_train_2_std = sf.transform(X_train_2)

In [21]:
print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [22]:
# Comprobar si las matrices estandarizadas son iguales
print(np.array_equiv(X_train_standarized, X_train_2_std))

True


In [23]:
X_test = np.array([[ 1., 0., 1.5]])

# Aplicar la estandarización de tus datos de entrenamiento.
X_test_std = sf.transform(X_test)

In [24]:
print(X_test_std)

[[0.         0.         0.93541435]]
